version: '3.4'
services:

  active-users-report-share:
    image: ${docker.share.image}:${alfresco.share.docker.version}
    environment:
      REPO_HOST: active-users-report-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
    deploy:
      resources:
        limits:
          memory: 2g
              
  active-users-report-acs:
    image: alfresco-content-services-active-users-report:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    deploy:
      resources:
        limits:
          memory: 4g
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - active-users-report-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - active-users-report-postgres
      
  active-users-report-postgres:
    image: postgres:13.1
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - active-users-report-db-volume:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1g
      
  active-users-report-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: active-users-report-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: active-users-report-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - active-users-report-ass-volume:/opt/alfresco-search-services/contentstore
      - active-users-report-ass-volume:/opt/alfresco-search-services/data
    deploy:
      resources:
        limits:
          memory: 2g
      
volumes:
  active-users-report-acs-volume:
    external: true
  active-users-report-db-volume:
    external: true
  active-users-report-ass-volume:
    external: true
